auth-server: http://localhost:9080/trias

server:
  port: 9081
  servlet:
    context-path: /trias-resource
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: all
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trias_cli?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: trias
    password: trias@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  
logging:
  level:
    com.trias.resouce.mapper: trace
